disabled_rules:
- trailing_whitespace

excluded:
- Pods
- INUBus/Supporting Files/AppDelegate.swift
- INUBus/Model/Objects.swift
- INUBus/Extension/CALayer+.swift
- INUBus/Search/TestViewController.swift

line_length:
  warning: 99
  error: 120
